INSERT INTO CATEGORIA (DESCRICAO) VALUES ('PRODUTO HIGIENE');

INSERT INTO CATEGORIA (DESCRICAO) VALUES ('PRODUTO LIMPEZA');

INSERT INTO CATEGORIA (DESCRICAO) VALUES ('CURSOS');

INSERT INTO USUARIO (NOME, EMAIL, SENHA) VALUES ('VICTOR', 'victor@gmail.com', '12345678');

INSERT INTO USUARIO (NOME, EMAIL, SENHA) VALUES ('TIAGO', 'tiago@gmail.com', '87654321');

INSERT INTO USUARIO (NOME, EMAIL, SENHA) VALUES ('LUCAS', 'lucas@gmail.com', '12341234');